# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mjnna_Delivery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mjnna_Delivery
pod 'Alamofire', '~> 5.2'
#
#pod 'GoogleMaps', '= 3.9.0'
#pod 'GooglePlaces', '= 3.9.0'
#
#pod 'Firebase/Core', '5.20.1'
#pod 'Firebase/Messaging'
#pod 'FirebaseInstanceID'
#
pod 'MaterialComponents/ActivityIndicator'
#
pod 'IQKeyboardManagerSwift'
#
pod 'FSPagerView'
#
pod 'TransitionButton'
pod 'MaterialComponents/TextFields'
pod 'SDWebImage'
#
pod 'lottie-ios'
#pod 'RealmSwift'
##amr
#pod 'Firebase/Analytics'
pod 'Cosmos'
pod 'SwiftyGif'
#
pod 'FloatingPanel'
pod 'GoogleSignIn'
pod 'FBSDKLoginKit'
end
